---
- hosts: all
  remote_user: beheerder
  become: true

  tasks:
  - name: Create a data container
    community.general.docker_container:
      name: mydata
      image: busybox
      volumes:
        - /data