---
- hosts: all
  remote_user: beheerder
  become: true

  tasks:
  - name: Jira Container Docker
    docker_container:
      name: Jira
      image: cptactionhank/atlassian-jira:latest
      state: started
      restart: yes
      detach: yes
      ports:
       # Publish container port 9000 as host port 8080
       - "8080:8080"