---
- hosts: all
  remote_user: beheerder
  become: true

  tasks:
    -name: Container test
     community.general.docker_container:
       name:
       image: nginx:latest
       state: started

  # - name: Jira Container Docker
  #   community.general.docker_container:
  #     name: Jira
  #     image: cptactionhank/atlassian-jira:latest
  #     state: started
  #     restart: yes
  #     detach: yes
  #     ports:
  #      # Publish container port 9000 as host port 8080
  #      - "8080:8080"