---
- hosts: Webservers
  remote_user: beheerder
  become: true
  tasks:
  - name: Updaten voor installatie
    apt:
      update_cache: yes
      register: bijwerken

  - name: server reboot ivm updates
    reboot:
    when: bijwerken.changed
    
  - name: ca-certificates installeren
    apt:
      name: ca-certificates
      state: latest
  - name: curl installeren
    apt:
      name: curl
      state: latest

  - name: software-properties-common installeren
    apt:
      name: software-properties-common
      state: latest
  
  - name: apt-transport-https installeren
    apt:


- name: Docker gpg repo key downloaden
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker GPG repo toevoegen
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Updaten i.v.m toevoegen Docker repo
   apt:
     update_cache: yes
     register: bijwerken

- name: server reboot voor de zekerheid
  reboot:
  when: bijwerken.changed
