---
- hosts: all
  tasks:
  - name: Map aanmaken om .exe in te zetten
    win_command: mkdir C:\Temp
    
  - name: Firefox Downloaden
    win_get_url:
      url: https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=nl
      dest: C:\Temp\Firefox.exe

  - name: Ensure Firefox is installed via win_package
    win_package:
      path: C:\Users\Testuser\Desktop\Firefox.exe
      product_id: Firefox
      become: true
      state: present
      user_name: Testuser
      user_password: Welkom01