---
- hosts: all
  tasks:
  - name: Map aanmaken om .exe in te zetten
    win_command: mkdir C:\Temp
    
  - name: Firefox Downloaden
    win_get_url:
      url: https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=nl
      dest: C:\Temp\Firefox.exe