---
- hosts: all
  remote_user: beheerder
  become: true
  tasks:
  - name: hostname aanpassen
    ansible.builtin.hostname:
       name: "{{hostname}}"

  - name: Reboot voor geval deze pending is
    reboot:
      reboot_timeout: 3600
  - name: alles updaten
    apt:
      name: "*"
      state: latest  
  - name: alles bijwerken van tevoren
    apt:
      upgrade: dist
  - name: apt-get update
    apt:
      update_cache: yes

  - name: server reboot ivm updates
    reboot:

  - name: Installeer update manager core
    apt:
      name: update-manager-core
      state: latest

  - name: bijwerken naar meest recente versie
    command: do-release-upgrade -d -f DistUpgradeViewNonInteractive
    when: ansible_facts['distribution_release'] <  "impish"
    register: versie

  - name: systeem herstarten
    reboot:
      reboot_timeout: 3600
    when: versie.changed
      
  - name: cache purgen
    apt:
      autoremove: yes
      purge: yes
  
  - name: voor de zekerheid herstarten
    reboot:
      reboot_timeout: 3600
