---
- hosts: all
 #vars:
 #ansible_user: '{{pmp_accountname}}'
 #ansible_pass: '{{lookup('passwordmanagerpro','{{pmp_resourcename}}','{{pmp_accountname}}'
  tasks:
   - name: Service controleren
     win_service:
       name: wuauserv
       register: service_info

     name: Registersleutel plaatsen
     win_regedit:
       path: HKLM\Software\KEMBIT
       name: Test
       data: "automatisch geplaatst door Jeroen"



