---
- hosts: all
  vars:
 #ansible_user: '{{pmp_accountname}}'
 #ansible_pass: '{{lookup('passwordmanagerpro','{{pmp_resourcename}}','{{pmp_accountname}}'
  machine: ansible_netbios_name 
  tasks:
  - name: user aanmaken met variabelen
    win_domain_user:
      name: '{{name}}'
      upn: '{{gebruikersnaam}}'
      firstname: '{{voornaam}}'
      surname: '{{achternaam}}'
      password: '{{wachtwoord}}'
      email: '{{gebruikersnaam}}'
      state: present
  
  - name: Facts weergeven   
    msg: "De hostname is:"   
       