---
- hosts: all
 #vars:
 #ansible_user: '{{pmp_accountname}}'
 #ansible_pass: '{{lookup('passwordmanagerpro','{{pmp_resourcename}}','{{pmp_accountname}}'
  tasks:
   - name: Copy a single file
    win_copy:
      src: C:\users\Administrator\Desktop\user.ps1
      dest: C:\Temp\user.ps1
   
   - name: Script runnen
     win_shell: C:\temp\user.ps1
       