---
- hosts: all
  vars:
 #ansible_user: '{{pmp_accountname}}'
 #ansible_pass: '{{lookup('passwordmanagerpro','{{pmp_resourcename}}','{{pmp_accountname}}'
  tasks:
  - name: user aanmaken met variabelen
    win_domain_user:
      name: '{{name}}'
      upn: '{{gebruikersnaam}}'
      firstname: '{{voornaam}}'
      surname: '{{achternaam}}'
      password: '{{wachtwoord}}'
      email: '{{gebruikersnaam}}'
      state: present
  
  - name: This will print the defined varible. hosts: all
    vars:
    fruit: apple tasks:
    name: Here we use Ansible debug module to print defined Variable.
    debug:
    var: fruit   
       