---
- hosts: all
  vars:
 #ansible_user: '{{pmp_accountname}}'
 #ansible_pass: '{{lookup('passwordmanagerpro','{{pmp_resourcename}}','{{pmp_accountname}}'
  tasks:
  - name: user aanmaken met variabelen
    win_domain_user:
      upn: '{{gebruikersnaam}}'
      firstname: '{{voornaam}}'
      surname: '{{achternaam}}'
      password: '{{wachtwoord}}'
      email: '{{email}}'
      state: present
       