---
- hosts: all
  tasks:
  - name: Overbodige packages verwijderen
    win_shell: Get-AppxPackage | Remove-AppxPackage

  - name: Installeer Firefox
    win_chocolatey:
      name: firefox
      state: present
      
  - name: systeem rebooten voor de zekerheid
    win_reboot:


