---
- hosts: all
  tasks:
  - name: Nieuws verwijderen
    win_shell: Get-AppxPackage *bingnews* | Remove-AppxPackage
  - name: Installeer Firefox
    win_chocolatey:
      name: firefox
      state: present
  - name: Mail en agenda verwijderen
    win_shell: Get-AppxPackage *windowscommunicationsapps* | Remove-AppxPackage
  
  - name: Edge verwijderen
    win_shell: Get-AppxPackage *MicrosoftEdge* | Remove-AppxPackage
  - name: systeem rebooten voor de zekerheid
    win_reboot:


