---
- hosts: all
  tasks:
  - name: Firefox verwijderen
    win_chocolatey:
      name: firefox
      state: absent
  - name: alle updates installeren
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      state: installed
    register: updates
  - name: Reboot host if required
    win_reboot:
    when: updates.reboot_required
