---
- hosts: Windows
  tasks:
  - name: alle updates installeren
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      state: installed
    register: updates
  - name: Reboot host if required
    win_reboot:
    when: updates.reboot_required
