---
- hosts: all
  tasks:
  - name: Windows eerst rebooten
    win_reboot:
  - name: Firefox installeren via MSI
    win_get_url:
      url: https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-US
      dest: C:\temp\Firefox.msi

  - name: Ensure Firefox is installed via win_package
    win_package:
      path: C:\temp\Firefox.msi
      state: present

      state: present
      user_name: Testuser
      user_password: Welkom01
  - name: alle updates installeren
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      state: installed
    register: updates
  - name: Reboot host if required
    win_reboot:
    when: updates.reboot_required
