---
- hosts: all
  tasks:
  - name: Firefox installeren via MSI
    win_package:
      path: https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=en-US
      product_id: Firefox  
      state: present
  - name: alle updates installeren
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      state: installed
    register: updates
  - name: Reboot host if required
    win_reboot:
    when: updates.reboot_required
